config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'spots#index'

  resources :spots, shallow: true do
    resources :mylists, only: [:create, :destroy], formats: 'js'
    resources :advices, shallow: true do
      resources :likes, only: [:create, :destroy], formats: 'js'
      resources :comments, only: [:create, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get    '/mylists', to: 'mylists#index'

  resources :users


end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :advices
  has_many :mylists
  belongs_to :create_user, class_name: "User"
  validates :place_name, presence: true,
            uniqueness: true
  validates :lat, presence: true
  validates :lng, presence: true
  acts_as_mappable :default_units => :kms

  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['place_name LIKE(?)', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end

  def self.default_picture
    "no_image.png"
  end

  def picture
    advice = advices.where.not(picture: nil).order(likes_count: :desc).first
    if advice.present?
      advice.picture
    else
      Spot.default_picture
    end
  end

  def mylist_user(user_id)
    mylists.find_by(user_id: user_id)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]
  def index
    @spots = Spot.search(params[:search])
    if params[:lat].present? && params[:lng].present?
      @spots = @spots.within(params[:distance], :origin => [params[:lat], params[:lng]]).by_distance(:origin => [params[:lat], params[:lng]])
      @distance = params[:distance]
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @sort_by = params[:sort_by];
    case @sort_by
    when "new"
      @advices = @spot.advices.order(created_at: :desc)
    else
      @advices = @spot.advices.order(likes_count: :desc)
    end
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = current_user.spots.build(spot_params)
    if @spot.save
      flash[:success] = "スポット作成ができました"
      redirect_to @spot
    else
      if params[:spot][:place_name].blank?
        flash.now[:danger] = "スポット名を入力してください"
      end
      if params[:spot][:lat].blank? || params[:spot][:lng].blank?
        flash.now[:warning] = "位置情報を入力してください"
      end
      render 'new'
    end
  end

private
  def spot_params
    params.require(:spot).permit(:place_name, :lat, :lng, :detail_comment)
  end

end

app/helpers/spots_helper.rb
require 'uri'
require 'active_support/core_ext'
module SpotsHelper

  def show_map_url(lat = '',lng = '')
    uri = URI(Settings.show_map.url)
    uri.query = {
      q: lat.to_s + "," + lng.to_s
    }.to_param
    uri.to_s
  end

  def designate_map_url()
    uri = URI(Settings.google_map_api.url)
    uri.query = {
      key: Settings.google_map_api.key,
      callback: "initMap"
    }.to_param
    uri.to_s
  end
end

app/views/spots/index.html.erb
<% provide :header_title, 'フォトフォーラム' %>

<div class="row">
  <div class="col s12 search-area">
    <%= form_tag(spots_path, method: "get", id: "search-form", class: "search_form") do %>
      <div class="input-field">
        <%= text_field_tag :search,  params[:search], :placeholder => 'キーワード検索' %>
        <%= hidden_field_tag 'distance', @distance, id: 'distance'%>
        <%= hidden_field_tag 'lat', nil,  id: 'lat' %>
        <%= hidden_field_tag 'lng', nil,  id: 'lng' %>
      </div>
    <% end %>
    <div class="buttons">
      <button id="search-submit" class="waves-effect waves-light btn"><i class="material-icons">search</i></button>
      <a class="waves-effect waves-light btn modal-trigger" href="#search-setting"><i class="material-icons">dehaze</i></a>
    </div>
  </div>
</div>

<% if @spots.blank? %>
  <session class="search_result">
    <div class="content">
      <p> 条件に一致する検索結果はありません。 </p>
    </div>
  </session>
<% end %>
<div class="spots row">
  <% @spots.each do |spot| %>
    <%= render 'layouts/spot', spot: spot %>
  <% end %>
</div>

<% if logged_in? %>
  <div class="fixed-action-btn">
    <%= link_to new_spot_url, class: "btn-floating btn-large waves-effect waves-light" do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
<% end %>

<div id="search-setting" class="modal search-setting">
  <div class="modal-content">
    <h4>検索の詳細設定</h4>
    <div class="setting-header">
      <div class="title">
        距離での絞り込み(km)
      </div>
      <div class="button">
        <div class="switch">
          <label>
            <input id="distance-button" type="checkbox" <% if @distance.present? then %>checked="checked"<% end %>>
            <span class="lever"></span>
          </label>
        </div>
      </div>
    </div>
    <p id="distance-range-field" class="range-field">
      <input id="distance-range" type="range" name="distance" min="1" max="20" value=<%= @distance %>>
    </p>
  </div>
  <div class="modal-footer">
    <a href="#!" id="finish-detail-settings" class="modal-action modal-close waves-effect waves-green btn-flat">完了</a>
  </div>
</div>

app/views/spots/new.html.erb
<% provide(:title, 'create Spot') %>
<% provide :header_title, 'スポット作成' %>

<session class="new_spot">
  <div class="row main">
    <%= form_for(@spot) do |f| %>
      <div class="col s12">
        <h3>スポット情報</h3>
        <div class="input-field">
          <%= f.label :place_name, "スポット名" %>
          <%= f.text_field :place_name %>
        </div>
        <div class="input-field">
          <%= f.label :detail_comment, "コメント" %>
          <%= f.text_area :detail_comment, class: "materialize-textarea" %>
        </div>
      </div>
      <div class="col s12">
        <h3>緯度・経度</h3>
        <p>スポットの場所をクリックして、位置を指定してください。</p>
        <div id="map"></div>
        <%= f.hidden_field :lat, :id => 'lat'%>
        <%= f.hidden_field :lng, :id => 'lng'%>
      </div>
      <div class="submit_button col s12">
        <%= button_tag "送信", type: "submit", class: "waves-effect waves-light btn" %>
      </div>
    <% end %>
  </div>
</session>
<script defer src=<%= designate_map_url %>></script>

app/views/spots/show.html.erb
<% provide(:title, @spot.place_name) %>
<% provide :header_title, "スポット詳細" %>

<session class="spot_detail">
  <div class="image-header">
    <%= image_tag @spot.picture, class: "responsive-img header-img" %>
    <div class="gray-background">
      <div class="iamge" style="background-image: url(<%== asset_url(@spot.picture) %>);"></div>
      <div class="gray"></div>
    </div>
    <div class="button-composer main">
      <div id="mylistid"><%= render :partial => "mylist", locals: { spot: @spot } %></div>
    </div>
  </div>
  <div class="row main">
    <div class="col s12">
      <h4><%= @spot.place_name %></h4>
    </div>
    <div class="col s12 l4 push-l8">
      <div class="row">
        <div class="col s8 m9 l6">
          <h5>詳細情報</h5>
        </div>
        <div class="col s4 m3 l6 map">
          <%= link_to "地図で開く",
                      show_map_url(@spot.lat,@spot.lng),
                      target: ["_blank"],
                      class: "waves-effect waves-light btn wide" %>
        </div>
        <div class="col s12">
          <p><%= @spot.detail_comment %></p>
        </div>
      </div>
    </div>
    <div class="col s12 l8 pull-l4">
      <div class="row">
        <div class="col s8 m9">
          <h5>アドバイス</h5>
        </div>
        <div class="col s4 m3 create_advice">
          <%= link_to "新規作成",
                      new_spot_advice_url(spot_id: @spot.id),
                      class: "waves-effect waves-light btn wide" %>
        </div>
        <div class="input-field col s12">
          <%= select_tag(:sort_by,
                        options_for_select([["新着順", "new"], ["いいね数", "hot"]], @sort_by),
                        onchange: "location.href='?sort_by=' + value;") %>
          <label>並び替え</label>
        </div>
        <% @advices.each do |advice| %>
          <div class="input-field col s12">
            <div class="card">
              <div class="card-image">
                <%= image_tag advice.picture.url, class: "responsive-img" if advice.picture? %>
              </div>
              <div class="card-content">
                <div class="advice-header">
                  <%= link_to advice.user.name, advice.user, class: "name" %>
                  <time class="grey-text"><%= advice.created_at.strftime('%Y年%m月%d日 %H:%M') %></time>
                </div>
                <p class="advice-text"><%= advice.comment %></p>
                <div id=<%= "like-button-#{advice.id}" %>>
                  <%= render :partial => "like", locals: { advice: advice} %>
                </div>
              </div>
              <div class="card-action">
                <%= link_to "detail", advice %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</session>