config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'spots#index'

  resources :spots, shallow: true do
    resources :mylists, only: [:create, :destroy], formats: 'js'
    resources :advices, shallow: true do
      resources :likes, only: [:create, :destroy], formats: 'js'
      resources :comments, only: [:create, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get    '/mylists', to: 'mylists#index'

  resources :users


end

app/models/Advice.rb
class Advice < ApplicationRecord
  belongs_to :spot
  validates :spot_id, presence: true
  validates :comment, presence: true
end

app/models/advice.rb
class Advice < ApplicationRecord
  belongs_to :spot
  belongs_to :user
  has_many :likes
  has_many :comments, dependent: :destroy
  validates :spot_id, presence: true
  validates :comment, presence: true, length: { maximum: 255 }
  mount_uploader :picture, PictureUploader

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  include AdvicesHelper
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:destroy, :edit, :update]

  def new
    @spot = Spot.find(params[:spot_id])
    @advice = @spot.advices.build
  end

  def create
    @spot = Spot.find(params[:spot_id])
    @advice = @spot.advices.build(advice_params)
    @advice = insert_place @advice if params[:advice][:picture] != nil
    @advice.user = current_user
    if @advice.save
      redirect_to controller: 'spots', action: 'show', id: @advice.spot_id
    else
      if params[:advice][:comment].blank?
        flash.now[:danger] = "コメントを入力して下さい"
      end
      render 'new'
    end
  end

  def show
    @advice = Advice.find(params[:id])
    @comments = Comment.where(advice_id: @advice.id)
    @comment = Comment.new
  end

  def edit
    @advice = Advice.find(params[:id])
  end

  def update
    @advice = Advice.find(params[:id])
    if @advice.update_attributes(advice_params)
       redirect_to controller: 'advices', action: 'show', id: @advice.id
    else
      render 'edit'
    end
  end

  def destroy
    @advice = Advice.find(params[:id])
    @advice.destroy
    flash[:success] = "advide deleted"
    redirect_to controller: 'spots', action: 'show', id: @advice.spot_id
  end

private
  def advice_params
    params.require(:advice).permit(:spot_id, :picture, :comment)
  end

  def correct_user
      @advice = current_user.advices.find_by(id: params[:id])
      redirect_to root_url if @advice.nil?
    end
end

app/helpers/advices_helper.rb
module AdvicesHelper
  require 'exifr/jpeg'
  def insert_place advice
    exifdata = EXIFR::JPEG.new "#{Rails.root}/public#{advice.picture.url}"
    lat = exifdata.gps
    if lat == nil
      advice.lat = nil
    else
      advice.lat = lat.latitude.to_f
      advice.lat *= (-1) if exifdata.to_hash[:gps_latitude_ref] == "S"
    end

    lng = exifdata.gps
    if lng == nil
      advice.lng = nil
    else
      advice.lng = lng.longitude.to_f
      advice.lng *= (-1) if exifdata.to_hash[:gps_longitude_ref] == "W"
    end
    return advice
  end
end

app/views/advices/edit.html.erb
<% provide(:title, "Edit advice") %>
<% provide :header_title, "アドバイス編集" %>

<session class="edit_advice">
  <div class="row main">
    <%= form_for(@advice) do |f| %>
      <div class="input-field col s12">
        <%= f.label :comment, "コメント", class: "active" %>
        <%= f.text_area :comment, class: "materialize-textarea", id: "advice-comment" %>
      </div>
      <div class="file-field input-field col s12">
        <div class="btn">
          <span>画像</span>
          <%= f.file_field :picture, accept: 'image/jpeg' %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
      <div class="submit_button col s12">
        <%= button_tag "送信", type: "submit", class: "waves-effect waves-light btn" %>
      </div>
    <% end %>
  </div>
</session>

app/views/advices/new.html.erb
<% provide(:title, 'advice') %>
<% provide :header_title, 'アドバイス作成' %>

<session class="new_advice">
  <div class="row main">
    <%= form_for([@spot, @advice]) do |f| %>
      <div class="input-field col s12">
        <%= f.label :comment, "コメント", class: "active" %>
        <%= f.text_area :comment, class: "materialize-textarea" %>
      </div>
      <div class="file-field input-field col s12">
        <div class="btn">
          <span>画像</span>
          <%= f.file_field :picture, accept: 'image/jpeg' %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
      <div class="submit_button col s12">
        <%= button_tag "送信", type: "submit", class: "waves-effect waves-light btn" %>
      </div>
    <% end %>
  </div>
</session>

app/views/advices/show.html.erb
<% provide(:title, 'advice') %>
<% provide :header_title, "アドバイス詳細" %>

<session class="advice_detail">
  <div class="image-header">
  <%= image_tag @advice.picture.url, :class => "responsive-img header-img" if @advice.picture? %>
  <div class="gray-background">
    <div class="iamge" style="background-image: url(<%== asset_url(@advice.picture) %>);"></div>
    <div class="gray"></div>
  </div>
  </div>
  <div class="row main">
    <div class="col s12 l8">
      <h5><%= @advice.spot.place_name %></h5>
      <div class="advice-header">
        <%= link_to @advice.user.name, @advice.user, class: "name" %>
        <time class="grey-text"><%= @advice.created_at.strftime('%Y年%m月%d日 %H:%M') %></time>
      </div>
      <p><%= @advice.comment %></p>
      <div class="buttons">
        <div class="like-button" id=<%= "like-button-#{@advice.id}" %>>
            <%= render :partial => "like", locals: { advice: @advice} %>
        </div>
        <% if @advice.lat != nil && @advice.lng != nil %>
          <%= link_to "地図で開く",
              show_map_url(@advice.lat,@advice.lng),
              target: ["_blank"],
              class: "waves-effect waves-light btn" %>
        <% end %>
      </div>
      <% if current_user == @advice.user && logged_in? %>
        <div class="buttons">
          <%= link_to "EDIT", edit_advice_path, class: "waves-effect waves-teal btn" %>
          <%= link_to "DELETE", @advice, class: "waves-effect waves-teal btn", method: :delete, data: { confirm: "You sure?" } %>
        </div>
      <% end %>
    </div>
    <div class="col s12 l4">
      <%= render 'application/comment', comments: @comments if @comments.present? %>

      <% if logged_in? %>
        <%= form_for([@advice, @comment]) do |f| %>
          <div class="input-field">
            <%= f.text_area :content, class: "materialize-textarea", id: "advice-comment" %>
            <label for="advice-comment">コメント</label>
          </div>
          <div class="buttons">
            <%= button_tag "送信", type: "submit", class: "waves-effect waves-light btn" %>
          </div>
        <% end %>

      <% end %>
    </div>

  </div>
</section>