config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'spots#index'

  resources :spots, shallow: true do
    resources :mylists, only: [:create, :destroy], formats: 'js'
    resources :advices, shallow: true do
      resources :likes, only: [:create, :destroy], formats: 'js'
      resources :comments, only: [:create, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get    '/mylists', to: 'mylists#index'

  resources :users


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
  #ページごとの完全なタイトルを返します
    def full_title(page_title = '')
      base_title = "フォトフォーラム" #暫定のプロダクト名
      if page_title.empty?
        base_title
      else
        page_title + " | " + base_title
      end
    end
end

app/views/application/_comment.html.erb
<section class="comments">
  <h5>コメント</h5>
  <ul class="collection">
    <% comments.each do |comment| %>
      <li class="collection-item">
        <div class="advice-header">
          <%= link_to comment.user.name, comment.user, class: "name" %>
          <time class="grey-text"><%= comment.created_at.strftime('%Y年%m月%d日 %H:%M') %></time>
        </div>
        <p><%= comment.content %></p>
        <% if current_user == comment.user %>
          <%= link_to "DELETE", comment, class: "waves-effect waves-teal btn", method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/application/_like.html.erb
<% if logged_in? %>
  <% if advice.like_user(current_user.id) %>
    <%= button_to like_path(advice.like_user(current_user.id)),
                  method: :delete,
                  class: "favorite waves-effect waves-teal btn-flat",
                  remote: true do %>
    <span class="pink-text"><i class="material-icons left">favorite</i><%= advice.likes_count %></span>
    <% end %>
  <% else %>
    <%= button_to advice_likes_path(advice),
                  class: "favorite waves-effect waves-teal btn-flat",
                  remote: true do %>
      <i class="material-icons left">favorite_border</i><%= advice.likes_count %>
      <% end %>
    <% end %>
  <% else %>
  <button class="favorite btn disabled">
    <i class="material-icons left">favorite</i><%= advice.likes_count %>
  </button>
<% end %>

app/views/application/_mylist.html.erb
 <% if logged_in? %>
  <% if spot.mylist_user(current_user.id) %>
    <%= button_to mylist_path(spot),
                  method: :delete,
                  class: "btn-floating btn-large waves-effect waves-light red",
                  remote: true do%>
      <span><i class="material-icons">star</i></span>
    <% end %>
  <% else%>
    <%= button_to spot_mylists_path(spot),
                  class: "btn-floating btn-large waves-effect waves-light red",
                  remote: true do%>
      <span><i class="material-icons">star_border</i></span>
    <% end %>
  <% end %>
<% end %>