config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'spots#index'

  resources :spots, shallow: true do
    resources :mylists, only: [:create, :destroy], formats: 'js'
    resources :advices, shallow: true do
      resources :likes, only: [:create, :destroy], formats: 'js'
      resources :comments, only: [:create, :destroy]
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get    '/mylists', to: 'mylists#index'

  resources :users


end

app/views/layouts/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Top', root_url %></li>
  <% if logged_in? %>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Mylist", mylists_path %></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Log in', login_path %></li>
    <li><%= link_to 'Sign Up', signup_path %></li>
  <% end %>
</ul>

<nav class="nav-wrapper">
  <span class="brand-logo"><%= yield :header_title %></span>
  <ul class="right">
    <li class="hide-on-med-and-down"><%= link_to 'Top', root_url %></li>
    <% if logged_in? %>
      <li class="hide-on-med-and-down"><%= link_to "Profile", current_user %></li>
      <li class="hide-on-med-and-down"><%= link_to "Mylist", mylists_path %></li>
      <li class="hide-on-med-and-down"><%= link_to 'Log out', logout_path, method: :delete %></li>
    <% else %>
      <li class="hide-on-med-and-down"><%= link_to 'Log in', login_path %></li>
      <li class="hide-on-med-and-down"><%= link_to 'Sign Up', signup_path %></li>
    <% end %>
    <li class="hide-on-large-only"><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">more_vert</i></a></li>
  </ul>
</nav>

app/views/layouts/_spot.html.erb
<%= link_to spot, class: "col s12 l6 xl4" do %>
  <div class="z-depth-2 hoverable" style="background-image: url(<%== asset_url(spot.picture) %>);">
    <h2><%= spot.place_name %></h2>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message|%>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
  <%= javascript_include_tag 'application'%>
</html>